apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: deployment-descriptors
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/kaizentm/kalypso-gitops
  ref:
    branch: dev
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deployment-descriptors
  namespace: flux-system
spec:
  interval: 30s
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: deployment-descriptors
  path: ./small/samples
  prune: true